services:
  # frontend: 
  #   image: node:19-alpine3.16
  #   command: npm i npm run watch
  # laravel:
  #   build: .
  #   # image: composer:latest
  #   # restart: always
  #   ports:
  #     - 8001:80
  #   # command: php artisan serve
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --init-file /var/lib/mysql/tpm/init.sql
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prubeaa_tecnica
      - MYSQL_USER=user
      - MYSQL_PASSWORD=carlos123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql